"""All shared constants for the Asteroids game."""

# Screen
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# Colors
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_GRAY = (128, 128, 128)
COLOR_DARK_GRAY = (64, 64, 64)
COLOR_YELLOW = (255, 255, 100)
COLOR_ORANGE = (255, 180, 50)
COLOR_RED = (255, 80, 30)

# Ship
SHIP_SIZE = 20
SHIP_ROTATION_SPEED = 270.0  # degrees per second
SHIP_THRUST = 200.0  # pixels per second squared
SHIP_FRICTION = 0.99
SHIP_MAX_SPEED = 400.0
SHIP_INVULNERABILITY_TIME = 3.0  # seconds
SHIP_BLINK_RATE = 0.1  # seconds between blink toggles
SHIP_LIVES = 3

# Bullets
BULLET_SPEED = 500.0
BULLET_LIFETIME = 1.0  # seconds
BULLET_MAX_ON_SCREEN = 4
BULLET_RADIUS = 2

# Asteroids
ASTEROID_LARGE_RADIUS = 40
ASTEROID_MEDIUM_RADIUS = 20
ASTEROID_SMALL_RADIUS = 10
ASTEROID_MIN_VERTICES = 8
ASTEROID_MAX_VERTICES = 12
ASTEROID_RADIAL_OFFSET_MIN = 0.7  # multiplier on radius
ASTEROID_RADIAL_OFFSET_MAX = 1.3

ASTEROID_LARGE_SPEED_MIN = 30.0
ASTEROID_LARGE_SPEED_MAX = 80.0
ASTEROID_MEDIUM_SPEED_MIN = 50.0
ASTEROID_MEDIUM_SPEED_MAX = 120.0
ASTEROID_SMALL_SPEED_MIN = 80.0
ASTEROID_SMALL_SPEED_MAX = 160.0

ASTEROID_SCORE_LARGE = 20
ASTEROID_SCORE_MEDIUM = 50
ASTEROID_SCORE_SMALL = 100

# Waves
WAVE_START_ASTEROIDS = 4
WAVE_INCREMENT = 2
WAVE_MAX_ASTEROIDS = 12
WAVE_SPAWN_MARGIN = 150  # minimum distance from ship when spawning

# Extra life
EXTRA_LIFE_SCORE = 10000

# Particles
PARTICLE_COUNT_EXPLOSION = 12
PARTICLE_COUNT_THRUST = 2
PARTICLE_SPEED_MIN = 50.0
PARTICLE_SPEED_MAX = 200.0
PARTICLE_LIFETIME_MIN = 0.3
PARTICLE_LIFETIME_MAX = 1.0
PARTICLE_THRUST_LIFETIME = 0.3
PARTICLE_THRUST_SPEED = 100.0

# Stars (background)
STAR_COUNT = 80

# HUD
HUD_FONT_SIZE = 36
HUD_SMALL_FONT_SIZE = 24
HUD_TITLE_FONT_SIZE = 64
HUD_MARGIN = 20

# High score file
import os
HIGHSCORE_FILE = os.path.expanduser("~/.asteroids_highscore")
